apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastnewsapi
  template:
    metadata:
      labels:
        app: fastnewsapi
    spec: # Pod spec
      containers:
      - name: fastapicontainer
        image: leocorrea/fast-news:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
    app: fastnewsapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
